// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BarLineModel: typeof import('./src/components/echartsModel/barLineModel.vue')['default']
    BarModel: typeof import('./src/components/BaseEchartsModel/BarModel.vue')['default']
    CylinderModel: typeof import('./src/components/BaseEchartsModel/CylinderModel.vue')['default']
    EarthModel: typeof import('./src/components/echartsModel/earthModel.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSubmenu: typeof import('element-plus/es')['ElSubmenu']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    FleetModel: typeof import('./src/components/echartsModel/fleetModel.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    LineModel: typeof import('./src/components/BaseEchartsModel/LineModel.vue')['default']
    Menus: typeof import('./src/components/menus/index.vue')['default']
    MenusItem: typeof import('./src/components/menus/menusItem.vue')['default']
    PictorialBarModel: typeof import('./src/components/BaseEchartsModel/PictorialBarModel.vue')['default']
    PieModel: typeof import('./src/components/BaseEchartsModel/PieModel.vue')['default']
    RadarModel: typeof import('./src/components/echartsModel/radarModel.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScatterModel: typeof import('./src/components/BaseEchartsModel/ScatterModel.vue')['default']
  }
}
